github: https://github.com/alireza-akbarzadeh
patreon: alireza akbarzadeh
open_collective: alireza-oss
ko_fi: alirezadev
tidelift: npm/astro-tailwind-react
community_bridge: astro-tailwind-react
liberapay: alirezadev
issuehunt: alirezadev
lfx_crowdfunding: astro-react-tailwind-kit
polar: alirezadev
buy_me_a_coffee: alirezadev
thanks_dev: alirezadev
custom: ['https://alirezadev.dev/sponsor', 'https://buymeacoffee.com/alirezadev']
